### ISSUE TITLE
Install fails on Ubuntu 19.10

### ISSUE THREAD

**Issue by dnaura** [Jay-Rad/Remotely#101]
Hello,
I tried to laucnh Remotely_Desktop on Ubuntu 19.10 (and also on previous versions and I have still the same error message related to .NET : 

```
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/var/tmp/.net/Remotely_Desktop/lgsrr4r2.4jb/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.19.10-x64
```
Maybe an Appimage including .NET would save the situation?

Thanks.
David

**Comment by Jay-Rad** [comment]
Hello.

You need to install the .NET Core runtime first, which can be found here:  https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1910

Alternatively, you can deploy it as a self-contained package, so the runtime wouldn't be required.  It's a much larger binary, though, since it contains the runtime with it.  I'll probably be switching to this once a build feature is out of preview that allows reducing the file size for self-contained binaries.

Thanks.
