### ISSUE TITLE
Registration or how to shoot yourself in the foot

### ISSUE THREAD

**Issue by i3laze** [Jay-Rad/Remotely#3]
1. As TCP:5000 is required to be published on the hosted server for remote clients to connect, **anyone** on the Internet might actually browse your webpage. How about splitting data port from web management? I'm not sure yet I wanna publish admin page outside.

2. Anyone can register..  that will apparently create a new organization. "Allow registration" checkbox better _exist_ and be disabled by default. Invites-only should be default mode.

3. Shooting in own foot: on Account - Organization page admin might untick own "Administrator" checkbox. That's enough to lose admin rights. It must be grayed for own account.

**Comment by Jay-Rad** [comment]
1.  As mentioned in my other answer, Remotely is configured to run behind IIS or Nginx.  The only ports exposed are those that IIS or Nginx are configured to listen on.  Direct access to the ASP.NET Core web host (Kestrel) isn't possible from the outside.  The client install script has the target host dynamically set based on the request's current URL.  You'll want to download the script from the publicly-accessible URL (or manually set it in the PS1 file).

2.  You can turn self-registration off in appsettings.json by setting the AllowSelfRegistration value.  I don't want this off by default since someone would have to turn it on anyway the first time they deploy and register themselves.  I don't yet have a mechanism for marking a user as a server administrator vs. an organization administrator, so I'm not ready to expose application-related settings.  But I do want to do that down the road.  For now, I might just show a reminder prompt on the first registration.

3.  Yeah, that's a problem.  I'll need to add that.

**Comment by Jay-Rad** [comment]
Resolved in commit 6560cae738b5a591e2c590dc64e658fa27c4a1b9.
