### ISSUE TITLE
Remove an entry from the grid

### ISSUE THREAD

**Issue by danmed** [Jay-Rad/Remotely#31]
Is there any way to remove an old entry from the grid list?

**Comment by Jay-Rad** [comment]
The "Remove" console command will remove selected devices.  If the service is still installed (which I'm assuming isn't the case here), they will come back on the next heartbeat.  To uninstall the service, use "Uninstall" command.

**Comment by swilkey** [comment]
Thanks for this Jared.

Since I'm currently having problems with agents uninstalling themselves randomly, and everytime you reinstall them it gets a new entry in the grid, I need an easy way to remove the obsolete ones.

I've tried using select -filter IsOnline=false
but it gives 0 devices selected.
and select -filter isonline=false
but it gives 0 devices selected.

I see there is a select -online but that isn't useful for this.  Can a select -offline be added so that offline clients can be removed?  Or is there another way short of selecting each of them by name?

The problem of selecting them by name is that if you don't remove the client before reinstalling it, you now have two clients (an offline one and an online one) with exactly the same name.  The only difference between them is that one is offline and the other is online.  So removing by name results in removing the online one as well, and then you have to wait for it to reappear before you can use it.

Thanks
Stephen

**Comment by swilkey** [comment]
I have found the solution so I'm documenting it here for future users.

select the machines you need to remove FIRST in the grid, then switch to the console.  Those machines will be selected still.  Now use the REMOVE command to remove those machines.  Simple really.

**Comment by empereira** [comment]
@swilkey 

Which console are you talking about?
