### ISSUE TITLE
Can this be used in presentation mode ?

### ISSUE THREAD

**Issue by giannik** [Jay-Rad/Remotely#33]
Firstly, this looks very cool. 
Can it be used for doing presentations remotely.?
For example , I am sharing my desktop with a colleague and I want to make someone else the presenter to show his desktop.
The other person shares his screen with me but I cannot control his desktop. Only see what he is showing me.
Thanks for this great project.
John.

**Comment by Jay-Rad** [comment]
Hi, John!

Thanks for the interest.

Unfortunately, it's not possible with Remotely.  I didn't design it with presentations and meetings in mind.

When controlling/viewing a remote computer, you're doing so in your browser.  You can't reverse the connection since a browser can't capture your screen.  At least, not without extensions.

I was thinking about taking the remote control from my older project (DoXM) and repurposing it to be a stand-alone screensharing/conferencing tool.  The Electron-based client, which I replaced in Remotely, would be ideal for that since it has screen capture and webcam stuff baked in.

Alas, I have no spare time.  :)

**Comment by giannik** [comment]
Ok, Jay-Rad.
Thanks for the update.
John.
