### ISSUE TITLE
Ok, I'm back again..

### ISSUE THREAD

**Issue by danmed** [Jay-Rad/Remotely#43]
How do i go about updating my install on Ubuntu?

I tried just re-downloading server.zip and unzipping it over the top, but not only did that bring back the register button (duh) but i couldn't log in anymore :(

**Comment by danmed** [comment]
How do i go about updating my install on Ubuntu?

**Comment by Jay-Rad** [comment]
Currently, that's the only way to update.

You want to make sure not to delete/overwrite your database or appsettings files.  By default, the database is Server.db.  This isn't included in the ZIP so shouldn't get overwritten (it gets created on first run).

For appsettings.json, it's best to make a copy of it in the same place, but call it appsettings.Production.json.  This will used automatically instead of appsettings.json and won't be overwritten during the update process.

**Comment by danmed** [comment]
thank you. will give it another go
