### ISSUE TITLE
Error when enabling recording

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#45]
Hi, I have enabled recording, I copied FFMPEG to Windows and the WWWROOT folder and made sure that application is running as a local admin.
When disconnecting from the client I get the following error:
The description for Event ID 1 from source Application cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Microsoft.AspNetCore.SignalR.HubConnectionHandler
Error when dispatching 'OnDisconnectedAsync' on hub.

System.Collections.Generic.KeyNotFoundException: The given key '8WyX1LdgRijO0ULH_SSPBw' was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at Remotely.Server.Services.RemoteControlSessionRecorder.StopProcessing(String viewerID) in E:\BitBucket\Remotely-master_RemovingPS\Server\Services\RemoteControlSessionRecorder.cs:line 114
   at Remotely.Server.Services.RCBrowserSocketHub.OnDisconnectedAsync(Exception exception) in E:\BitBucket\Remotely-master_RemovingPS\Server\Services\RCBrowserSocketHub.cs:line 142
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.HubOnDisconnectedAsync(HubConnectionContext connection, Exception exception)

the message resource is present but the message is not found in the string/message table

What could be wrong ?!

**Comment by Jay-Rad** [comment]
It looks like this error would happen if there was issue starting ffmpeg and piping into it.  When the remote control connection disconnects, it finalizes the write operations to the MP4 file and closes the ffmpeg process.  This error is occurring because the process information isn't there (since it failed to launch).

I missed capturing logs for the area where the initial error is occurring, which is why they're not in the logs.  I'll add that on the next commit.

The problem could be that ffmpeg.exe is in the wrong location.  If by "wwwroot", you mean the folder that's inside the server ZIP, that's the wrong location.  You want it to be one folder up from wwwroot, where the "Remotely_Server.dll" file is located.

Also, I would recommend against running Remotely (or any web app process) as a local admin.  You want to give these processes only the privileges they need to run properly, and no more.  It's best to start with the IIS app pool's default rights, then add permissions specifically to the ffmpeg file and the Recordings folder.

Let me know if that helps!

**Comment by Busbar2297** [comment]
I was configuring it as Administrator to avoid any permissions issues.

Somehow I feed it is related to https://github.com/Jay-Rad/Remotely/issues/47, I will test and let you know.

**Comment by Busbar2297** [comment]
I was correct, I need to do the following:
- use Post in API login and not the get method.
- Change App pool account to be an account with a username/password not the default pool account
- change the connect as account to be the same account.

after that it worked.

**Comment by Jay-Rad** [comment]
Awesome.  Glad to hear it's working now!
