### ISSUE TITLE
Elevate Session

### ISSUE THREAD

**Issue by rodolphopedra** [Jay-Rad/Remotely#71]
How to elevate session with administrative session/user?

For example: possible to access login window and administrative tasks.

**Comment by Jay-Rad** [comment]
If the service is installed for unattended access, you should have access to everything.

When connecting via the attended access (Remotely_Desktop.exe), it depends on how the application was launched.  If the account that launched it is an administrator, it will attempt to run elevated and do a UAC prompt.  If a standard user account launches it, it will be a normal process and will have limited access.

If it's elevated, you'll be able to interact with other elevated applications, such as Task Manager and Microsoft Management Console snap-ins (Computer Management, Services, Devices Manager, etc.).

Even if it's elevated, you still won't be able to interact with full-screen UAC and the Windows logon screen.  Those require special privileges that can only be obtained by launching the process from a service.

You might wonder, "But TeamViewer is able to with TeamViewer Quick Support."

TeamViewer does some semi-shady stuff to accomplish it.  When you launch TVQS and accept the UAC prompt, it uses the elevation to temporarily install a service and raise its privilege level even further.  You can see the service and other files it extracts in %temp%\TeamViewer\, and the new tv_w32.exe and tv_x64.exe processes running as the SYSTEM account within your user session.

Example:
![TeamViewer Privilege Escalation](https://i.imgur.com/1D6s8SD.jpg)

There's nothing inherently malicious about this, but it's giving itself more privilege than you realize.  I could also do this, but won't because I think it's wrong.

**Comment by rodolphopedra** [comment]
There's nothing inherently malicious about this, but it's giving itself more privilege than you realize. I could also do this, but won't because I think it's wrong.

How do I do this???

**Comment by Jay-Rad** [comment]
You would need to install the service via the PowerShell installer to gain full access.

I might look into adding a button to elevate it to service-level privileges.  But I don't want to do it automatically on start-up without the user's explicit consent.

**Comment by Jay-Rad** [comment]
I've added this to the options menu.

![](https://i.imgur.com/RT1LZyk.png)

**Comment by introspection3** [comment]
> 我已将此添加到选项菜单中。
> 
> ![](https://camo.githubusercontent.com/4072bc79b4e8dd9e836985931885f8f749c8dcb67206868fafd8783571db2e2f/68747470733a2f2f692e696d6775722e636f6d2f5254314c5a796b2e706e67)

first we must run it as admin,then elevate to service ,but then came across
![image](https://user-images.githubusercontent.com/12368358/174427865-f9ce7897-1aa7-4c7a-8c4b-e698ecbe8324.png)
