### ISSUE TITLE
RemoteControlSessionLimit isn't observed

### ISSUE THREAD

**Issue by McChicken2020** [Jay-Rad/Remotely#73]
At least with on-demand sessions, I'm finding that RemoteControlSessionLimit is ignored entirely. I set it to 1 to save bandwidth but looks like you can still do as many sessions as you'd like.

**Comment by Jay-Rad** [comment]
Thanks for catching this!

Initially, the on-demand (attended) sessions were intentionally left out of it.  Attended remote control sessions can't be tied to an organization if they aren't logged in, so I couldn't use them in the total count.  Now that I have the RemoteControlRequiresAuthentication option, it makes more sense to include them.

I changed it so attended sessions are counted toward the total too (if the viewer is logged in).  To ensure the max session count is completely enforced, use the RemoteControlRequiresAuthentication option too.  :)

**Comment by McChicken2020** [comment]
Awesome, thanks. Is there a way for the warning to be more obvious for maxxing out connections? When you're on the computer list, if you try to connect the Console shows the warning and you see the exclamation point, but it's easy to miss if you already have a notice that something new is in the console... Maybe a toast popup?

**Comment by Jay-Rad** [comment]
Actually, I did add a toast notification for that on January 22.  If you've updated since then and still aren't seeing it, you may need to do a hard refresh on the page (Ctrl + F5 on Windows).

A word of caution, there was a breaking change to the agent auto-update feature around that time.  There's a warning on the releases page.  When upgrading to/past that version, agents need to be manually redeployed.  It shouldn't happen again.
