### ISSUE TITLE
Address Problem

### ISSUE THREAD

**Issue by robulanetteam** [Jay-Rad/Remotely#83]
Hello! There is one problem, I can’t understand how to solve it. When I access from my local network, everything works fine for me. As soon as I log in through NAT, all the computers in my list disappear, and I can not add computers to the list that are behind NAT.
When you log in behind NAT, the list of computers is empty
Perhaps you need to specify an external address somewhere in the system settings?

**Comment by swilkey** [comment]
Hi, I'm not specifying anything like that in my setup so I'd like to confirm details of your setup.  In my setup, my remotely server is in the cloud, and my clients are all behind NATs and I'm also behind another NAT when remote controlling them.

Where is your remotely server located, and where are your clients located?

**Comment by robulanetteam** [comment]
My server is located inside the local network and is accessible to clients both through NAT and through the local network. When working on a local network - my computers are added and work fine. But I can’t add computers for NAT, and I also don’t see a list of my computers inside the local network when I log in to my server for NAT.

**Comment by swilkey** [comment]
Sorry, at this point I'm not sure.  I'll butt out here and let Jared respond.

**Comment by Jay-Rad** [comment]
The only thing I can think of that could be a problem with Remotely itself was the issue I fixed in https://github.com/Jay-Rad/Remotely/issues/72.

Are you running an old version where that's still a problem?  You can check by installing Remotely agent from the external address (NAT).  Then check the Host property in "C:\Program Files\Remotely\ConnectionInfo.json".  Is it https or http?

Another thing you could try is creating an account on https://app.remotely.one and installing the agent.  If it works from there, then it's a server/network issue that I probably can't help with.
