### ISSUE TITLE
Do we have to rebuild the database to upgrade

### ISSUE THREAD

**Issue by swilkey** [Jay-Rad/Remotely#90]
Hi Jared,

I'm just wondering if we even need to rebuild the database in order to upgrade?  I've unpacked Bridge.zip as instructed.  I'm not sure how we know if all the clients have upgraded or not apart from waiting a day or so unless we look at the properties of each agent individually to see the agent version number.

After that I understand we're supposed to rebuild the database, but what information is contained in the database that is important?  Can we just reinstall the server?  I haven't created any groups yet so the only configuration is the server settings which are in a json file which I already followed your instructions to ensure that they are permanent between upgrades.  Or is there other configuration information somewhere that is important?

So I'm just wondering if I can simply unpack the new server files over the existing ones?

I'm also unclear about the ZIP files that were in Bridge.zip - these ZIP files are the agent service.  I understood from testing (not from documentation as I couldn't find anything) that the url of my server is contained in them if I build it using publish.ps1, but that if I just copy the release ones from source it will not contain that.  I understand that the GUID of the server is encoded in the name of the file when you download it from the downloads section of a remotely server and that the agent installer extracts that from the file name.  So I'm puzzled how I can just copy the files from Bridge.zip and they will work.  Understanding that there might be something about bridge.zip that is special just for this migration, under normal circumstances for a server upgrade, should I be building these files with publish.ps1 or should I be copying them directly from source?

Thanks for clarifying
Stephen

**Comment by Jay-Rad** [comment]
A rebuild of the database is necessary to upgrade past 2020.02.14.  If you reinstall the server without modifying the database, it will stop working.

The reason for this is because, as the underlying data models in the server code change, migration files are generated automatically.  These migration files tell the database how to alter itself to keep in sync with the code.  Database schema must match models in code.

This normally happens automatically without ever noticing it.  However, SQLite has limitations.  There are several operations it can't perform automatically.  So I'd need to write a bunch of extra, very tedious code to drop database tables and move data round to reconstruct it.  I don't have time to do that, unfortunately. 

I could have also used PostgreSQL or MS SQL to avoid this.  They can handle all the migration operations automatically.  But then it'd require anyone using Remotely to set up a full database.

So I settled on SQLite, knowing that I'd be having to do full wipes during beta.  Once I'm close to leaving beta, the data models will be stable and won't need to be changed, so database wipes won't be necessary.

The agent service does not have any specific information compiled into it.  It gets all its info from ConnectionInfo.json.

The database contains your organization info.  Everything is tied to it.  Your account is tied to it, as well as each device. All that info needs to be present for things to work.  The device info in the database has a verification token that was generated on first install.  If the server doesn't respond with it every time a SignalR (websocket) connection is made, the device won't accept any commands or remote control.  If a command or remote control is attempted without the server first providing that verification, the agent will uninstall itself.

**Comment by Jay-Rad** [comment]
If possible, it would likely be easier to just delete the database, upgrade the server, and reinstall the agents.  This type of change probably won't happen again.

**Comment by swilkey** [comment]
Oh, I see.  Thanks for clarifying.

------ Original Message ------

**Comment by swilkey** [comment]
Ok. thanks

------ Original Message ------

**Comment by Jay-Rad** [comment]
I forgot to mention that you can check the agent version using GetVersion web command.  You can select all to see a list of all of them at once.

**Comment by swilkey** [comment]
thanks!  that is a great help
