### ISSUE TITLE
Reset user password from SQLite

### ISSUE THREAD

**Issue by graphixillusion** [Jay-Rad/Remotely#95]
Heya there. As the title says, how to reset an user password (even the administrator ones) from within the SQLiteDatabaseBrowser? I saw that the users infos are stored in the "RemotelyUsers" table. I tried to delete the hashed password value but that didn't work. Any clue?

**Comment by Jay-Rad** [comment]
Hiya.  It can't be done through the database itself.  You'll need to go into Account - Organization and get a password reset link for the user.

**Comment by tlhonmey** [comment]
Not only is it possible, it's fairly trivial.
I'm going to keep this high-level since there are multiple database options and they're all subtly different.  Consult the SQL reference for your database as needed.

Open the database.  Examine the RemotelyUsers table.
Find the user entry you want to change the password for.
Generate a new .net hashed password.  I used https://dotnetfiddle.net/aaMWMC

Then something like:
UPDATE RemotelyUsers set PasswordHash="AAT6tGHjbj0o4IMNchedXGj0owhz+uztfxEV/jRARIt250NgAjDrwdnxBC/xXB3xtQ==" WHERE UserName="YourUserName" ;

This will set the user named "YourUserName" to a password of "test".

Feel free to generate a hash for whatever password you prefer.  Note that this can also be used to bypass the password complexity requirements, but don't do that unless you actually understand password strength.

**Comment by lucent-sea** [comment]
Thanks for the follow-up.  :)
